// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// binned_method_cpp_wrap
NumericVector binned_method_cpp_wrap(NumericVector bin_id, NumericVector intensity);
RcppExport SEXP _PeakSorter_binned_method_cpp_wrap(SEXP bin_idSEXP, SEXP intensitySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type bin_id(bin_idSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type intensity(intensitySEXP);
    rcpp_result_gen = Rcpp::wrap(binned_method_cpp_wrap(bin_id, intensity));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PeakSorter_binned_method_cpp_wrap", (DL_FUNC) &_PeakSorter_binned_method_cpp_wrap, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_PeakSorter(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
