# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Internal function called as part of the binned algorithm. Not meant for the
#' end user.
#' 
#' In the following, i is 0, 1, 2, ...
#' @param bin_id A vector where bin_id[i] represents the bin number of peak i.
#' @param intensity A vector where intensity[i] represents the intensity of peak i.
#' @return Vector of i indicating the order of peaks as sorted by the binned method
binned_method_cpp_wrap <- function(bin_id, intensity) {
    .Call(`_PeakSorter_binned_method_cpp_wrap`, bin_id, intensity)
}

